interface ConfigEntry {
  path: String
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}

type ConfigInteger implements ConfigEntry {
  path: String
  integer: Int
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigString implements ConfigEntry {
  path: String
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigFloat implements ConfigEntry {
  path: String
  float: Float
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigBoolean implements ConfigEntry {
  path: String
  boolean: Boolean
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigObject implements ConfigEntry {
  path: String
  object: JSONType
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigIntegerList implements ConfigEntry {
  path: String
  integers: [Int]
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigStringList implements ConfigEntry {
  path: String
  strings: [String]
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigFloatList implements ConfigEntry {
  path: String
  floats: [Float]
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigBooleanList implements ConfigEntry {
  path: String
  booleans: [Boolean]
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}
type ConfigObjectList implements ConfigEntry {
  path: String
  objects(offset: Int = 0, limit: Int = 100): [ConfigObject]
  stringValue: String
  updateTime: Int
  updateTimeString: String
  generation: Int
  count: Int
}
type DeletedConfigEntry {
  path: String
  updateTime: Int
  updateTimeString: String
  generation: Int
}

input ConfigEntryInputV3 {
  integer: ConfigIntegerInput
  string: ConfigStringInput
  boolean: ConfigBooleanInput
  float: ConfigFloatInput
  object: ConfigObjectInput
  integer_list: ConfigIntegerListInput
  stringList: ConfigStringListInput
  booleanList: ConfigBooleanListInput
  floatList: ConfigFloatListInput
  objectList: ConfigObjectListInput
}

input ConfigIntegerInput {
  path: String!
  integer: Int!
}
input ConfigStringInput {
  path: String!
  string: String!
}
input ConfigBooleanInput {
  path: String!
  boolean: Boolean!
}
input ConfigFloatInput {
  path: String!
  float: Float
}
input ConfigObjectInput {
  path: String!
  object: JSONType
}
input ConfigIntegerListInput {
  path: String!
  integerList: [Int]!
}
input ConfigStringListInput {
  path: String!
  stringList: [String]!
}
input ConfigBooleanListInput {
  path: String!
  booleanList: [Boolean]!
}
input ConfigFloatListInput {
  path: String!
  floatList: [Float]
}
input ConfigObjectListInput {
  path: String!
  objectList: [JSONType]
}

type Query {
  configUserInteger(applet: String, path: String!): ConfigInteger
  configUserBoolean(applet: String, path: String!): ConfigBoolean
  configUserFloat(applet: String, path: String!): ConfigFloat
  configUserString(applet: String, path: String!): ConfigString
  configUserObject(applet: String, path: String!): ConfigObject
  configUserIntegerList(applet: String, path: String!): ConfigIntegerList
  configUserBooleanList(applet: String, path: String!): ConfigBooleanList
  configUserFloatList(applet: String, path: String!): ConfigFloatList
  configUserStringList(applet: String, path: String!): ConfigStringList
  configUserObjectList(applet: String, path: String!): ConfigObjectList
  configUserEntries(applet: String, paths: [String!]!, timeout: Int): [ConfigEntry]

  configBusinessAccountInteger(businessAccountId: ID, path: String!): ConfigInteger
  configBusinessAccountBoolean(businessAccountId: ID, path: String!): ConfigBoolean
  configBusinessAccountFloat(businessAccountId: ID, path: String!): ConfigFloat
  configBusinessAccountString(businessAccountId: ID, path: String!): ConfigString
  configBusinessAccountObject(businessAccountId: ID, path: String!): ConfigObject
  configBusinessAccountIntegerList(businessAccountId: ID, path: String!): ConfigIntegerList
  configBusinessAccountBooleanList(businessAccountId: ID, path: String!): ConfigBooleanList
  configBusinessAccountFloatList(businessAccountId: ID, path: String!): ConfigFloatList
  configBusinessAccountStringList(businessAccountId: ID, path: String!): ConfigStringList
  configBusinessAccountObjectList(businessAccountId: ID, path: String!): ConfigObjectList
  configBusinessAccountEntries(businessAccountId: ID): [ConfigEntry!]!
}
type Mutation {
  saveConfigUserBoolean(applet: String, path: String!, boolean: Boolean!): ConfigBoolean
  saveConfigUserBooleanList(applet: String, path: String!, booleanList: [Boolean]!): ConfigBooleanList
  saveConfigUserFloat(applet: String, path: String!, float: Float!): ConfigFloat
  saveConfigUserFloatList(applet: String, path: String!, floatList: [Float]!): ConfigFloatList
  saveConfigUserString(applet: String, path: String!, string: String!): ConfigString
  saveConfigUserStringList(applet: String, path: String!, stringList: [String]!): ConfigStringList
  saveConfigUserInteger(applet: String, path: String!, integer: Int): ConfigInteger
  saveConfigUserIntegerList(applet: String, path: String!, integerList: [Int]!): ConfigIntegerList
  saveConfigUserObject(applet: String, path: String!, object: JSONType!): ConfigObject
  saveConfigUserObjectList(applet: String, path: String!, objectList: [JSONType]!): ConfigObjectList
  saveConfigUserEntries(applet: String, entries: [ConfigEntryInput]!): [ConfigEntry]
  deleteConfigUserEntry(applet: String, path: String!): DeletedConfigEntry

  saveConfigBusinessAccountInteger(businessAccountId: ID!, path: String!, integer: Int!): ConfigInteger
  saveConfigBusinessAccountBoolean(businessAccountId: ID!, path: String!, boolean: Boolean!): ConfigBoolean
  saveConfigBusinessAccountFloat(businessAccountId: ID!, path: String!, float: Float!): ConfigFloat
  saveConfigBusinessAccountString(businessAccountId: ID!, path: String!, string: String!): ConfigString
  saveConfigBusinessAccountObject(businessAccountId: ID!, path: String!, object: JSONType!): ConfigObject
  saveConfigBusinessAccountIntegerList(businessAccountId: ID!, path: String!, integerList: [Int!]!): ConfigIntegerList
  saveConfigBusinessAccountBooleanList(businessAccountId: ID!, path: String!, booleanList: [Boolean!]!): ConfigBooleanList
  saveConfigBusinessAccountFloatList(businessAccountId: ID!, path: String!, floatList: [Float!]!): ConfigFloatList
  saveConfigBusinessAccountStringList(businessAccountId: ID!, path: String!, stringList: [String!]!): ConfigStringList
  saveConfigBusinessAccountObjectList(businessAccountId: ID!, path: String!, objectList: [JSONType!]!): ConfigObjectList
  saveConfigBusinessAccountEntries(businessAccountId: ID!, entries: [ConfigEntryInput!]!): [ConfigEntry!]!
  deleteConfigBusinessAccountEntry(businessAccountId: ID!, path: String!): DeletedConfigEntry
}
